name: TNTBow
version: 1.0-SNAPSHOT
main: fr.tonnom.tntbow.Main
api-version: '1.21'
author: TonNom
description: Un plugin qui ajoute un arc à TNT explosif surpuissant !
commands:
  givetntbow:
    description: Donne l'arc TNT spécial.
    permission: tntbow.use
