name: Build Paper Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Recuperer le code source
      uses: actions/checkout@v4

    - name: Configurer Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Compiler le plugin a toute vitesse
      run: mvn clean package --batch-mode --errors

    - name: Telecharger le fichier .jar
      uses: actions/upload-artifact@v4
      with:
        name: TNT-Bow-Plugin
        path: target/*.jar
